version: '3.8'

services:
  java-calculator:
    build:
      context: ./java-calculator
      dockerfile: Dockerfile
    image: scientific-calculator-java:latest
    container_name: calculator-java
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
